services:
  webapp:
    container_name: webapp_c
    image: webapp:${WEBAPP_ENVIRONMENT}
    build:
      context: ./Website
      target: ${WEBAPP_ENVIRONMENT}
    depends_on:
      - database
    ports:
      - ${WEBAPP_PORT}:3000
    develop:
      watch:
        - action: sync
          path: ./Website
          target: /webapp
          ignore:
            - Website/node_modules/
            - .git
        - action: rebuild
          path: Website/package.json
        - action: rebuild
          path: Website/Dockerfile
        - action: rebuild
          path: ./docker-compose.yml

  database:
    container_name: database_c
    image: database:${WEBAPP_ENVIRONMENT}
    build: ./Database
    ports:
      - ${DATABASE_PORT}:8000
    develop:
      watch:
        - action: sync
          path: ./Database
          target: /database
          ignore:
          - Database/node_modules
          - .git
        - action: rebuild
          path: Database/package.json
        - action: rebuild
          path: Database/Dockerfile
