services:
  webapp:
    container_name: webapp_c
    image: webapp:${WEBAPP_ENVIRONMENT}
    build:
      context: ./Website
      target: ${WEBAPP_ENVIRONMENT}
    depends_on:
      - database
    ports:
      - ${WEBAPP_PORT}:3000
    develop:
      watch:
        - action: sync
          path: ./Website
          target: /webapp
          ignore:
            - node_modules
            - .git
        - action: rebuild
          path: Website/package.json
        - action: rebuild
          path: Website/Dockerfile

  database:
    container_name: database_c
    image: database:${WEBAPP_ENVIRONMENT}
    build: ./Database
    ports:
      - ${DATABASE_PORT}:8000
    volumes:
      - database_volume:/database/data:rw
    develop:
      watch:
        - action: sync
          path: ./Database
          target: /database
          ignore:
          - node_modules
          - data
          - .git
        - action: rebuild
          path: Database/package.json
        - action: rebuild
          path: Database/Dockerfile

volumes:
  database_volume: