services:
  webapp:
    container_name: webapp_c
    build: .
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile