services:
  webapp:
    container_name: webapp_c
    build:
      context: ./Website
      target: ${WEBAPP_MODE}
    depends_on:
      - database
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./Website
          target: /webapp
          ignore:
            - Website/node_modules/
            - .git
        - action: rebuild
          path: Website/package.json
        - action: rebuild
          path: Website/Dockerfile
        - action: rebuild
          path: ./docker-compose.yml

  database:
    container_name: database_c
    build: ./Database
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./Database
          target: /database
          ignore:
          - Database/node_modules
          - .git
        - action: rebuild
          path: Database/package.json
        - action: rebuild
          path: Database/Dockerfile
